name: shell commands

on : 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run oneline script
        # run : sh ./github-actions-script.sh
        run: echo Awadh Prajapat 

      - name: run multi line script
        run : |
          echo 1. What is in the directory?
          ls -a
          echo
          echo 2. Is java installed?
          java --version
          echo 
          echo 3. Is git installed?
          git --version
          echo
          
