name: shell commands

on : 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run oneline script
        run : sh ./github-actions-script.sh

      - name: run multi line script
        run : |
          echo pre build disc space
          
          echo here is what is in the folder
          ls -a 