name: shell commands

on : 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run oneline script
        run : echo hello world

      - name: run multi line script
        run : |
          echo Awadh 
          echo Prajapat
          ls -a 
          echo
          echo is java installed
          java --version
          echo is git installed
          git --version
          echo what environment variable is available
          env