name: shell commands

on : [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "Awadh"
      - name: multiline script
        run: |
          node -v 
          npm -v
          java --version
      - name: python command
        run: |
          print("Awadh Prajapat")
        shell: python

  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: directory powershell
        run: Get-Location
      - name: directory bash
        run: pwd
        shell: bash 